### ISSUE TITLE
Devolucion TP4

### ISSUE THREAD

**Issue by carlosalbertopardo** [colomfernando/programacion-web-coderhouse#4]
Hola Fernando, como estas?
Me parece que me mandaste el ej 5.  El 4 era el de los alumnos y Maradona. Fijate si podes corregir el link.
Saludos!

**Comment by colomfernando** [comment]
Hola Carlos, disculpa el error. Acabo de subir los links del tp 4 y 5  su respectivas clases.

Gracias!
